# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4a82ae9d5e4e8838b8b8850c171b24dfafb7e63e97a69f95137fcbf819b08523664f9b07cea1c63d6f490397e8aaaebdaeb140523d2634bf1fc2ba6c9d5b6400

test:
  secret_key_base: a931724f52bf41852804fa4d2bac5b273cac434d6e1aec5efe81d74646c0f317130cfdd59c4b338ec17ca39b8a3cb586f732f1bd10317ffa32cbd3bf6828b083

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
